### ISSUE TITLE
Can you do it for "liked songs"? [Remove Unplayable Songs]

### ISSUE THREAD

**Issue by MickgClone** [Resxt/Spicetify-Extensions#1] opened 2022-12-09 13:15 UTC
Not much of a writer for github so sorry if anything looks off.

So, this extension works but I can't get it to work with the "liked songs" list cause it just won't let ya right click it.
I'm not a big playlist maker.
So, unless I'm missing something, is there a way for you to make it work with that? If not, that's fine.
I'm just a little annoyed at how you can't right click the "liked songs" list and I'm guessing that's just a Spotify issue but people just don't talk about it... I guess?

Either way, thanks for reading!

**Comment by Resxt** [comment] 2022-12-09 19:40
Hello @MickgClone 

There is certainly a way to do that but I need to adapt the code to support both playlists and liked songs.
I didn't think about liked songs when creating this to be honest.

I will look into this whenever I have time this weekend.
Thanks for the recommendation :)

**Comment by MickgClone** [comment] 2022-12-09 19:55
I don't know how much other people create playlists, so maybe it's that?
Though, I'm just guessing. This extension would help when some songs just get removed and then Shuffle+ decides to somehow keep trying to play those songs a few times, so this would help a lot!

Thank you for putting your time into this and I'm willing to wait however long it takes!

Also, can the "Liked Songs" be somehow made to be "Right-Clickable"? (Don't know the right word)
I'm just wondering if it's possible because I'm just a little curious though you don't have to explain it if you don't want to and the "Liked Songs" just seem like a playlist in their own way too.

**Comment by Resxt** [comment] 2022-12-09 22:28
@MickgClone Maybe. I just started developing extensions on Spicetify recently so I don't know most possibilities.
In theory yes you can add what's called an event listener which does something whenever you right click, for example.
But in practice I need to see if I can implement something like this in Spicetify. We'll see

**Comment by MickgClone** [comment] 2022-12-10 01:28
Well, if you do get interested in making an extension for that, I feel like it would fix some problems but I don't know if it works like that. 
Honestly, would be glad to be able to use it like it was a playlist because that's what I think of it as but if it doesn't appear anytime soon, it'll be fine.

But still, thank you for looking into this!

**Comment by Resxt** [comment] 2022-12-11 14:29
@MickgClone it was longer than expected because I tried to keep the same behavior than playlists which was pretty hard for me.
I ended up finding an in-between solution to make it similar while not being too hard/annoying to develop for me.

Whenever you right click on the Liked Songs button, in your sidebar, a popup will be displayed with a button allowing you to remove unplayable songs in your liked songs playlist. I'm not too happy about how it looks and all but at least it works and it's pretty much the same than with regular playlists.
The README has been updated as well with those instructions

Now we need to wait for some hours/days so that the update gets pushed on Spicetify's marketplace.
To my knowledge it should automatically update on your side without you noticing.

Edit: it should be updated now

**Comment by MickgClone** [comment] 2022-12-11 19:18
I just now got around to seeing it. For me, the goal was just to make it so that it was possible to remove unplayable songs from "Liked Songs".
So, this works for me but thank you for trying to make it similar to playlists. Also, I'm just now noticing this but I think there is a little delay between the "Liked Songs" vs playlists but it's only just seconds apart but thought you would like to know.
I don't know how that stuff works and that shouldn't bother anyone.
The popup that appears is fine for me as the "Liked Songs" never had a context menu so it's good. Do still wish for it but you're doing this when you're free and I wouldn't want ya to hate the extension. This extension is still helpful!

Thank you for putting your time into it! I'll still hope for the day that it's easier to deal with that list.
Do I go ahead close this or....?

**Comment by Resxt** [comment] 2022-12-11 19:25
The delay is because the API used is different and has a lower limit (50 songs per request for liked songs and 100 songs per request for regular playlists.
Also I'm sending one request after the other which isn't the most optimal for loading times.
Also obviously it depends on how much songs you have. Removing songs from a 200 songs playlist is faster than doing the same with a 1000 songs playlists.

Maybe one day I'll take the time to try and optimize the loading times but yeah that's how it is.
Since you confirmed that you got what you want I'm closing this issue 😃

**Comment by eturkes** [comment] 2024-01-28 14:56
Hi, I'm having trouble with this still, as can be seen in the screenshot. I installed the extension from the marketplace and I'm able to use the extension with other playlists. My spotify version is ```1.2.26.1187.g36b715a1-0```.

![image](https://github.com/Resxt/Spicetify-Extensions/assets/25193231/6dc0209a-7e48-4325-82e6-f0e5faeb4573)

**Comment by Resxt** [comment] 2024-01-28 15:28
Hello @eturkes 

This issue exists now because when I wrote the extension you couldn't right click liked songs on Spotify and therefore I added my own event handler for it which worked fine.
Now that Spotify has its own (if I believe what I see on your screenshot) I need to move the option to another area.

I'll do that whenever I have time, thanks for the report.
I am personally using an older Spotify version (before the UI rework) so I am unable to test those changes myself which is why reports like this are really useful for me, thanks

**Comment by eturkes** [comment] 2024-01-28 16:22
@Resxt I see! No problem, thank you for looking into it.

**Comment by Resxt** [comment] 2024-02-14 16:14
Hey @eturkes sorry for the delay I got busy with other projects and things IRL.
I just updated the extension, moving the feature for liked songs to the profile menu (clicking on your profile picture)

I did several tests and it works fine on my side
Let me know if there's any issue or anything

**Comment by eturkes** [comment] 2024-02-14 17:33
@Resxt thank you for this!
I just updated the extension through Marketplace by removing it and re-adding it. In Marketplace I see that it says it was last updated on today's date, so that should've worked I guess.
But I cannot see the option that you mention, below is an image of what's in my profile menu:

![image](https://github.com/Resxt/Spicetify-Extensions/assets/25193231/c7224d31-448d-443b-8b64-ad0bc7258d23)

**Comment by eturkes** [comment] 2024-02-14 17:38
FYI, that Shuffle+ extension works properly with "Liked Songs". As in I can right-click on "Liked Songs" and Shuffle+ shows up as an option

**Comment by Resxt** [comment] 2024-02-14 18:28
That's good to know but I'll keep the option in that menu to avoid issues in the future I think. It's easier that way
I could be wrong but from what I know fetching update date and fetching the actual updated file is not the same on the marketplace. So you'll have to wait a few days for jsdelivr to fetch the new files, which should then update automatically for you

Edit: got it confirmed. Gotta wait (or install manually until it updates)

**Comment by eturkes** [comment] 2024-02-15 12:13
@Resxt I see, thanks for the info. Yes by now it's updated and I can see the button you've added in profile menu. Sadly, it does not seem to work. I've confirmed that I have unplayable songs among my liked songs, but they are not getting removed. If I add those songs to a playlist though, I can confirm that your extension does work to remove it from there.

**Comment by eturkes** [comment] 2024-02-15 12:14
I spoke too soon!! It did remove them after a couple mins. I guess since i have 10k songs it just took a while for the program to thrawl through it. But it works, thank you so much!

**Closed as completed** 2024-02-15 14:41 UTC
Labels: enhancement, feature added
